create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'parent' check (role in ('parent','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.child_profiles (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references public.profiles(id) on delete cascade,
  display_name text not null,
  avatar_key text,
  level integer not null default 1,
  xp integer not null default 0,
  streak_days integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  world_key text not null,
  title_vi text not null,
  summary_vi text not null,
  order_index integer not null,
  xp_reward integer not null default 20,
  content jsonb not null default '{}'::jsonb,
  is_published boolean not null default false
);

create table if not exists public.lesson_progress (
  child_id uuid not null references public.child_profiles(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  status text not null default 'not_started' check (status in ('not_started','in_progress','completed')),
  score integer,
  completed_at timestamptz,
  primary key (child_id, lesson_id)
);

create table if not exists public.puzzles (
  id uuid primary key default gen_random_uuid(),
  theme text not null,
  fen text not null,
  solution_uci text[] not null,
  explanation_vi text,
  difficulty integer not null default 1 check (difficulty between 1 and 5),
  xp_reward integer not null default 5,
  is_published boolean not null default false
);

create table if not exists public.puzzle_attempts (
  id bigint generated by default as identity primary key,
  child_id uuid not null references public.child_profiles(id) on delete cascade,
  puzzle_id uuid not null references public.puzzles(id) on delete cascade,
  is_correct boolean not null,
  duration_ms integer,
  attempted_at timestamptz not null default now()
);

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.child_profiles(id) on delete cascade,
  pgn text not null,
  result text,
  opponent_type text not null default 'local',
  summary jsonb not null default '{}'::jsonb,
  played_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.child_profiles enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.puzzle_attempts enable row level security;
alter table public.games enable row level security;

create policy "read own profile" on public.profiles for select using (auth.uid() = id);
create policy "update own profile" on public.profiles for update using (auth.uid() = id);
create policy "manage own children" on public.child_profiles for all using (auth.uid() = parent_id) with check (auth.uid() = parent_id);
create policy "manage child lesson progress" on public.lesson_progress for all using (
  exists(select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())
) with check (
  exists(select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())
);
create policy "manage child puzzle attempts" on public.puzzle_attempts for all using (
  exists(select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())
) with check (
  exists(select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())
);
create policy "manage child games" on public.games for all using (
  exists(select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())
) with check (
  exists(select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())
);
